### ISSUE TITLE
Add a script for supremenewyork

### ISSUE THREAD

**Issue by kfichter** [kfichter/OpenATC#1]
Add an ATC script for supremenewyork

**Comment by kfichter** [comment]
Added, but in beta. Needs to be improved.

**Comment by th3l0b3** [comment]
stoked about this.  currently getting errors when running it.
Edited the file to look for jackets (currently looking for one that is sold out so i can see that reply, then i was going to move on to actually trying to purchase something.

# Inputs
keywords_category = ['jackets']  # Demo stuff, feel free to change
keywords_model = ['Color Blocked Quilted Jacket', 'Twill Zip Parka']
keywords_style = ['Orange']


  File "supremenewyork.py", line 32
    print('Finding matching products... \n', end='')
                                                ^
SyntaxError: invalid syntax

**Comment by kfichter** [comment]
Sorry, it's a mistake in the code. It should be 
`print('Finding matching products... \n', end='"')`. Can someone fix? I'm not at my computer.

**Comment by kfichter** [comment]
`end=""`

**Comment by th3l0b3** [comment]
changed it and still get the same kind of error:

root@wpad:/opt/OpenATC/Scripts# python supremenewyork.py 
  File "supremenewyork.py", line 34
    print('Finding matching products... \n', end="")
                                                                        ^
SyntaxError: invalid syntax

**Comment by kfichter** [comment]
Ah oops - it's Python 3 specific. Needs to be rewritten for Python 2.

**Comment by th3l0b3** [comment]
word, after i installed:
python3-urllib3
python3-requests
python3-bs4 

I was able to get the output:
root@wpad:/opt/OpenATC/Scripts# python3.4 supremenewyork.py 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
Finding matching products... 
1.2834524329999795



Is that the time it took to "find" items?  also, should lt let me know that it could not purchase/item sold out...etc?  sorry for the 20 questions but thanks for the quick replies.

**Comment by kfichter** [comment]
Yeah, that's the time it took to find stuff. This hasn't been worked on very hard but I'm going to get the thing working by this Thursday. Feel free to contribute and make pull requests.

**Comment by ra-rock** [comment]
anyone have any info on how we would go about scraping for early links?
