### ISSUE TITLE
Add a script for footlocker

### ISSUE THREAD

**Issue by kfichter** [kfichter/OpenATC#3]

**Comment by My-kal** [comment]
added, but is check out is not complete

**Comment by kar21us** [comment]
Traceback (most recent call last):
  File "C:\Users\kartikeya\Downloads\OpenATC-master\OpenATC-master\Scripts\footlocker.py", line 159, in <module>
    if size[-1] is not "5":
NameError: name 'size' is not defined

why am i getting that when running footlocker

**Comment by domshyra** [comment]
I'm currently getting selenium issues when trying to run the footlocker script. I was going to try and port in for eastbay and champs website. But I cannot get the footlocker.py to run correctly. 

`Traceback (most recent call last):
  File "footlocker.py", line 197, in <module>
    driver = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x10dcd76d0>> ignored
`

**Comment by kfichter** [comment]
@domshyra this project needs to be restructured to separate dev files from master files. Footlocker isn't really ready yet.

**Comment by domshyra** [comment]
@kfichter I got it to work with chrome by adding the chromedriver and adding the path to it.
`driver = webdriver.Chrome('/path/to/chromedriver')` 
It loaded up the page but gave me a session expired when I went to check out. Granted I just downloaded this yesterday and haven't used it too much. Also I have a fake CSV number on the account, but it seems to be getting there.

**Comment by My-kal** [comment]
@domshyra I can look into it tomorrow. I don't have my computer rn.

**Comment by domshyra** [comment]
@My-kal no worries! If you guys have slack or something I'd love to start contributing. Don't have much python experience but I can figure it out. Email is the same as my username at gmail. Thanks again. This project is great.

**Comment by My-kal** [comment]
@domshyra yah, we have slack, https://slack-invitation-app.herokuapp.com 

PM me there if you need me

**Comment by Roylamer** [comment]
is there any way to avoid the problem of session expired problem?  
I will make a slight modification to see whether it is  ok. My idea is that I will try to use request login than process the original script(except the part of selenium). Thank you very much!

**Comment by Kream1g** [comment]
@My-cal I would love to join slack to help contribute to this

**Comment by My-kal** [comment]
@kream1g unfortunately, that exact slack group no longer exists. I can add you to a new one, however it isn't focused on OpenATC. If you want in the new slack, leave your email and I'll send you an invite.

**Comment by samtruong200** [comment]
@My-kal  can you invite me to the new slack? samtruong200@gmail.com

**Comment by Kream1g** [comment]
@my-Kal angelojones1989@gmail.com

**Comment by Silayman** [comment]
@my-Kal thesliayman@gmail.com

**Comment by My-kal** [comment]
@Silayman @Kream1g @samtruong200 invites have been sent

**Comment by 9-9-0** [comment]
@my-kal m.gao.1@protonmail.com

**Comment by Roylamer** [comment]
@my-Kal wchan757@gmail.com

**Comment by harrizon** [comment]
@My-kal zach.harrison55@gmail.com

**Comment by innawe** [comment]
@My-kal itux169@gmail.com please add me

**Comment by hankco** [comment]
@My-kal hankmanos25@gmail.com

**Comment by demazzidesign** [comment]
@My-kal diaz.mario23@gmail.com

**Comment by joeymickss** [comment]
Please send invitation, Let's rock 2017 :) 
JoeyMcBratney@gmail.com

**Comment by mloft** [comment]
Send an invitation, im a comp sci major and would love to get in on this 
mloft5998@gmail.com

**Comment by DarrenDouglas22** [comment]
Interested in helping out! Please send an invite to darrenadouglas@gmail.com

**Comment by darshan2670** [comment]
dpayda@gmail.com

**Comment by darshan2670** [comment]
@My-kal dpayda@gmail.com

**Comment by lockhartd** [comment]
Please send me an invite, I want to help out ibanefssb@gmail.com

**Comment by DarkSkull91** [comment]
Please send me an invite too, ale9108@gmail.com

**Comment by jalex1** [comment]
Computer Science major here would love to have an input joshalex010@gmail.com
