### ISSUE TITLE
Adidas Captcha

### ISSUE THREAD

**Issue by anthony6608** [kfichter/OpenATC#30]
First off, thank you guys for even considering us folks. We know how this sneaker game is so its amazing to see you taking the time out to help others. If I can do anything please let me know.

I noticed the Adidas script seems to be working, as far as the output its saying it added the item to cart, etc. I have a dummy CC in their so won't know if it checked out. Also doesn't seem to support account login so I can log in to verify that the shoes been added to cart.

Is it possible to add Captcha? Either bypass or have it open in a browser for user to solve? Also if possible add account support so we can specify our account details?

Thanks again.

**Comment by 9-9-0** [comment]
AFAIK, Mykal and others in the slack are working on implementing a solution to the captcha. Right now the two options being considered are:

1) Use a paid 3rd-party human-solving captcha service
2) Extract the captcha from the page and allow the user to solve it.

Option 1 would fare better for those running multiple instances. Option 2 may be faster.

As a note, the current Adidas Script posts your credit card info to their server but does not actually check out the item. Currently, the Adidas checkout page packages your session information that was sent over and redirects that, along with uniquely generated keys, towards CyberSecure, a 3rd-party payment processor.
