### ISSUE TITLE
SOMEONE HELP ME PLEASE!!

### ISSUE THREAD

**Issue by itslit23** [kfichter/OpenATC#35]
How do I use this stuff to make a bot. Am i supposed to copy this stuff and put in Python. If so where do I put it and how do I put it in. I want this to be done for adidas, so I can try and get the BAPExNMD shoes releasing on November 26th. Thanks in advance!!!

**Comment by My-kal** [comment]
Join the slack group https://slack-invitation-app.herokuapp.com

**Comment by itslit23** [comment]
ok
