### ISSUE TITLE
Can someone explain it to me PLEASE? Supreme Bot

### ISSUE THREAD

**Issue by Sydroce** [kfichter/OpenATC#36]
Please help me to get my Supreme Bot working :(
 
I have tried everything, but when I use "supremenewyork.py", it says:

     "Found "......" at "supremenewyork.com/...."
      Adding "....." to Cart"

But it doesn't add it into my cart when I'm on supremenewyork.com on Google Chrome or Mozilla Firefoxe.

And when I use the "supremenewyork_v3.py", it says

     "Run time of job "on_time (trigger: date[2016-09-01 10:59:59 EDT], next run at: 2016-09-01 10:59:59 EDT)" was missed by 82 days, 19:25:50.070004"

Please help me in order to get the Bot working. I would REALLY appreciate it.

Sincerely Yours,
KM

**Comment by harveylewis** [comment]
The first message means is just notifying that the products been added. It doesn't add to a physical basket like you usually would with supreme. It sends a request to add to a virtual basket (basically an intangible one) that you cannot see

**Comment by Sydroce** [comment]
@harveylewis So if I also let it fill in my information, it will check out the item by itself and I will get a email by Supreme? Or doesn't the program work yet?

**Comment by My-kal** [comment]
Join the slack and ask questions there: https://slack-invitation-app.herokuapp.com
